### ISSUE TITLE
Migrate to Github

### ISSUE THREAD

**Issue by grtjn** [marklogic-community/grove-cli#1]
- check and resolve pending PR's
- import from internal bitbucket to github
- add deprecation message to bitbucket
- migrate unresolved PR's
- prune unnecessary branches
- check README, package*, NOTICE/LICENSE
- republish under `@marklogic-community`?

**Comment by grtjn** [comment]
Isn't the cli already published under ml-community?

**Comment by grtjn** [comment]
Patrick, i think it would be best if you take a lead on this, maybe together with Marianne. I think it should be fairly straight-forward to migrate to Github, once that PR in bitbucket is out of the way.

Oh, I ran a local test with grove new using the https github link to grove-vue-template in the code, and that seemed to work just fine!

**Comment by patrickmcelwee** [comment]
To be clear, one subtask for this is to point the templates to the versions now on Github.

**Comment by patrickmcelwee** [comment]
going to make a separate issue for pointing templates to Github, since everything else is done.
