### ISSUE TITLE
How To Deploy Production app 

### ISSUE THREAD

**Issue by garyvidal** [marklogic-community/grove-cli#12]
I am currently trying to deploy the front/backend code and having a hard time understanding how to deploy the dist and configuring the proxy for fetch?  The documentation is sparse to describe how to configure the proxy for /api calls

**Comment by grtjn** [comment]
Could describe in a bit more detail what you have tried?

The general idea is that you use `npm run build` in the ui folder to create a dist of the frontend, and then you run the middle-tier with a GROVE_UI_BUILD_PATH pointing to that dist or a copy of it. If you then start the middletier with `npm run start:prod` it should check the ui path and report if it works or not.

**Comment by garyvidal** [comment]
First I ran npm build to create the dist folder.
I ran "npm install -g serve"
I ran "serve dist"
In another console I run the npm start in middle-tier folder.
But from my understanding the webpack is running the dist folder and because it is not using vue.config.js so the proxy settings are not being used, so it 404 on all /api calls

**Comment by grtjn** [comment]
Just skip the serve bit, and let the middle-tier serve the statics. We use webpack only for dev purposes..

**Comment by garyvidal** [comment]
Sorry for being dense, but how would you achieve this?
Copy into middle tier, configure some configuration?
There is like a million ways I guess to skin this cat.

**Comment by dmcassel** [comment]
Sounds like some more detailed documentation would be helpful.

**Comment by garyvidal** [comment]
Thanks Geert,
Following your instructions. It seemed to work once you configure the GROVE_UI_BUILD_PATH
I have the following directory structure
project/ui/ui
project/ui/middle-tier

Here is the steps I followed:
project/ui>npm run-script "build"
>cp ui/dist ../middle-tier/*
>update GROVE_UI_BUILD_PATH in .env directory
seems like it works

**Comment by grtjn** [comment]
I typically use pm2 to run in production. The pm2 ecosystem config that comes with the template has a predefined ui build path property pointing to ../ui/dist/, saving you a copy.

Then again, for docker you need to copy it, so worth keeping it if you plan moving there..

**Comment by grtjn** [comment]
@dmcassel, we are working on the docs on github.io, but we have a lot on our plates.. :)
